# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d7be57b587c9d0d2b3cbf236e23f1d121ab54b476c3931617e84e1dcb9e5779cca9094285c87e061f0b6bd90229a44105ea571956559b884cd0519bdd94bedb

test:
  secret_key_base: 407d7aef6ff4ff3ed77d52194ec692d6e6e77dff19f0746283af699af1118fd30d6c51cf5ffb56774103184cf1d0c277a1982190d5431c42b4a409cf527a155b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
